### PR TITLE
Superoperators

### PR DESCRIPTION
**Pull request by dkrasa**
Correct relations between (at least some) super operators were added. RelaxationTensor now inherits from SuperOperator.

### CODE REVIEW

**Comment by tmancal74** [comment]
The problem seems to be in different precision of output in printing the transition energies and dipole moments in exciton_report() of Aggregate. Please, set the precision of the output in Aggregate and update tests.

**Comment by dkrasa** [comment]
I have fixed the exciton_report() formatting and its tests. Local tests run well.

**Comment by tmancal74** [comment]
Still some problems with formatting. This time it is LabSetup. We print a result of DFunction at() method, which is a numpy array (in this case). Try to check the numpy.set_printoptions call in the quantarhei.core.managers.py on line 129. Maybe including the legacy option will fix the output again.

**Comment by dkrasa** [comment]
My local tests now fail somewhere, where they did not before, but the previous problem seems to be fixed. I need to see response from the CI server.

**Comment by dkrasa** [comment]
It passed on Travis-CI, but it seems that their version of numpy does not behave as it should. It seems not to react to the legacy='1.13' setting which should suppress the + sign in the complex number representation. I will try to ask trevis to install numpy 1.14.0 to get rid of the legacy problems

**Comment by dkrasa** [comment]
Now I removed the troubled test altogether. It was not necessary at that point at all.

**Comment by tmancal74** [comment]
I accept the pull request. I take it as a message from this discussion that we should go over all __str__ methods defined in Quantarhei and thoroughly test their output and make sure that they give consistent representation.

**Pull request merged**
